Ecommerce/Ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include

#To show media files
from django.conf import settings
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Shop_Application.urls')),
    path('account/', include('Login_Application.urls')),
    path('order/', include('Order_Application.urls')),
    path('payment/', include('Payment_Application.urls'))
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Ecommerce/Order_Application/urls.py
from django.urls import path
from Order_Application import views

app_name = 'Order_Application'


urlpatterns = [
     path('add/<pk>/', views.add_to_cart, name="add"),
     path('cart/', views.cart_view, name="cart"),
     path('remove/<pk>/', views.remove_from_cart, name="remove"),
     path('increase/<pk>/', views.increase_cart, name="increase"),
    path('decrease/<pk>/', views.decrease_cart, name="decrease"),
]

Ecommerce/Shop_Application/urls.py
from django.urls import path
from Shop_Application import views

app_name = 'Shop_Application'

urlpatterns = [
    path('', views.Home.as_view(), name='home'),
    path('product/<pk>/', views.ProductDetail.as_view(), name='product_detail'),
    path('Accessories', views.Accessories, name='accessories'),
    path('Clothing', views.Clothing, name='clothing'),
    path('EyeWear', views.EyeWear, name='eyewear'),
    path('Electronics', views.Electronics, name='electronics'),
    path('Timepieces', views.Timepieces, name='timepieces'),
]

Ecommerce/Shop_Application/models.py
from django.db import models

# Create your models here.
class Category(models.Model):

	title = models.CharField(max_length=20)
	created = models.DateTimeField(auto_now_add=True)

	def __str__(self):
	    return self.title

	class Meta:
	    verbose_name_plural = "Categories"
        # verbose so the name in the admin panel is categories


class Product(models.Model):

	mainimage = models.ImageField(upload_to='Products')
	name = models.CharField(max_length=264)
	category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name='category')
	preview_text = models.TextField(max_length=200, verbose_name='Preview Text')
	detail_text = models.TextField(max_length=1000, verbose_name='Description')
	price = models.FloatField()
	old_price = models.FloatField(default=0.00)
	created = models.DateTimeField(auto_now_add=True)

	def __str__(self):

		return self.name

	class Meta:
		ordering = ['-created',]
	    #So that the latest add is shown first

Ecommerce/Shop_Application/views.py
from django.shortcuts import render

# Import views
from django.views.generic import ListView, DetailView

# Models
from Shop_Application.models import Product

# Mixin
from django.contrib.auth.mixins import LoginRequiredMixin
# Create your views here.



class Home(ListView):
    model = Product
    template_name = 'Shop_Application/Home.html'

class ProductDetail(LoginRequiredMixin, DetailView):
    model = Product
    template_name = 'Shop_Application/product_detail.html'


def Accessories(request):
	data = 5
	listdata = Product.objects.filter(category=data).order_by('name')
	dic = {'listdata': listdata}
	return render(request,'Shop_Application/Accessories.html',context=dic)


def Clothing(request):
	data = 2
	listdata = Product.objects.filter(category=data).order_by('name')
	dic = {'listdata': listdata}
	return render(request,'Shop_Application/Clothing.html',context=dic)


def EyeWear(request):
	data = 4
	listdata = Product.objects.filter(category=data).order_by('name')
	dic = {'listdata': listdata}
	return render(request,'Shop_Application/EyeWear.html',context=dic)



def Electronics(request):
	data = 1
	listdata = Product.objects.filter(category=data).order_by('name')
	dic = {'listdata': listdata}
	return render(request,'Shop_Application/Electronics.html',context=dic)



def Timepieces(request):
	data = 6
	listdata = Product.objects.filter(category=data).order_by('name')
	dic = {'listdata': listdata}
	return render(request,'Shop_Application/Timepieces.html',context=dic)

Ecommerce/templates/Shop_Application/Accessories.html
{% extends 'base.html' %}
{% block body_block %}

<div class="container my-5">
  <h2 class="my-5">Featured Products</h2>
  <div class="row">
    {% for product in listdata %}
    <div class="col-md-6 col-sm-12 col-lg-3">
      <figure class="card card-product">
        <div class="img-wrap">
          <a href="{% url 'Shop_Application:product_detail' pk=product.pk %}">
          <img src="/media/{{product.mainimage}}" style="width:100%; height:300px;">
          </a>
        </div>
        <figcaption class="info-wrap">
          <h6 class="title"><a href="{% url 'Shop_Application:product_detail' pk=product.pk %}">{{product.name}}</a></h6>
          <div class="action-wrap">
            <div class="price-wrap h5">
              <span class="price-new">&#2547; {{product.price|floatformat:2}}</span>
              <span class="price-old"><strike>&#2547; {{product.old_price|floatformat:2}}</strike></span>
            </div>
          </div>
        </figcaption>
      </figure>
    </div>
    {% endfor %}
  </div>
</div>

{% endblock %}

Ecommerce/templates/Shop_Application/Clothing.html
{% extends 'base.html' %}
{% block body_block %}

<div class="container my-5">
  <h2 class="my-5">Featured Products</h2>
  <div class="row">
    {% for product in listdata %}
    <div class="col-md-6 col-sm-12 col-lg-3">
      <figure class="card card-product">
        <div class="img-wrap">
          <a href="{% url 'Shop_Application:product_detail' pk=product.pk %}">
          <img src="/media/{{product.mainimage}}" style="width:100%; height:300px;">
          </a>
        </div>
        <figcaption class="info-wrap">
          <h6 class="title"><a href="{% url 'Shop_Application:product_detail' pk=product.pk %}">{{product.name}}</a></h6>
          <div class="action-wrap">
            <div class="price-wrap h5">
              <span class="price-new">&#2547; {{product.price|floatformat:2}}</span>
              <span class="price-old"><strike>&#2547; {{product.old_price|floatformat:2}}</strike></span>
            </div>
          </div>
        </figcaption>
      </figure>
    </div>
    {% endfor %}
  </div>
</div>

{% endblock %}

Ecommerce/templates/Shop_Application/Electronics.html
{% extends 'base.html' %}
{% block body_block %}

<div class="container my-5">
  <h2 class="my-5">Featured Products</h2>
  <div class="row">
    {% for product in listdata %}
    <div class="col-md-6 col-sm-12 col-lg-3">
      <figure class="card card-product">
        <div class="img-wrap">
          <a href="{% url 'Shop_Application:product_detail' pk=product.pk %}">
          <img src="/media/{{product.mainimage}}" style="width:100%; height:300px;">
          </a>
        </div>
        <figcaption class="info-wrap">
          <h6 class="title"><a href="{% url 'Shop_Application:product_detail' pk=product.pk %}">{{product.name}}</a></h6>
          <div class="action-wrap">
            <div class="price-wrap h5">
              <span class="price-new">&#2547; {{product.price|floatformat:2}}</span>
              <span class="price-old"><strike>&#2547; {{product.old_price|floatformat:2}}</strike></span>
            </div>
          </div>
        </figcaption>
      </figure>
    </div>
    {% endfor %}
  </div>
</div>

{% endblock %}

Ecommerce/templates/Shop_Application/EyeWear.html
{% extends 'base.html' %}
{% block body_block %}

<div class="container my-5">
  <h2 class="my-5">Featured Products</h2>
  <div class="row">
    {% for product in listdata %}
    <div class="col-md-6 col-sm-12 col-lg-3">
      <figure class="card card-product">
        <div class="img-wrap">
          <a href="{% url 'Shop_Application:product_detail' pk=product.pk %}">
          <img src="/media/{{product.mainimage}}" style="width:100%; height:300px;">
          </a>
        </div>
        <figcaption class="info-wrap">
          <h6 class="title"><a href="{% url 'Shop_Application:product_detail' pk=product.pk %}">{{product.name}}</a></h6>
          <div class="action-wrap">
            <div class="price-wrap h5">
              <span class="price-new">&#2547; {{product.price|floatformat:2}}</span>
              <span class="price-old"><strike>&#2547; {{product.old_price|floatformat:2}}</strike></span>
            </div>
          </div>
        </figcaption>
      </figure>
    </div>
    {% endfor %}
  </div>
</div>

{% endblock %}

Ecommerce/templates/Shop_Application/Home.html
{% extends 'base.html' %}
{% block body_block %}

<div class="container my-5">
  <h2 class="my-5">Featured Products</h2>
  <div class="row">
    {% for product in object_list %}
    <div class="col-md-6 col-sm-12 col-lg-3">
      <figure class="card card-product">
        <div class="img-wrap">
          <a href="{% url 'Shop_Application:product_detail' pk=product.pk %}">
          <img src="/media/{{product.mainimage}}" style="width:100%; height:300px;">
          </a>
        </div>
        <figcaption class="info-wrap">
          <h6 class="title"><a href="{% url 'Shop_Application:product_detail' pk=product.pk %}">{{product.name}}</a></h6>
          <div class="action-wrap">
            <div class="price-wrap h5">
              <span class="price-new">&#2547; {{product.price|floatformat:2}}</span>
              <span class="price-old"><strike>&#2547; {{product.old_price|floatformat:2}}</strike></span>
            </div>
          </div>
        </figcaption>
      </figure>
    </div>
    {% endfor %}
  </div>
</div>

{% endblock %}

Ecommerce/templates/Shop_Application/Timepieces.html
{% extends 'base.html' %}
{% block body_block %}

<div class="container my-5">
  <h2 class="my-5">Featured Products</h2>
  <div class="row">
    {% for product in listdata %}
    <div class="col-md-6 col-sm-12 col-lg-3">
      <figure class="card card-product">
        <div class="img-wrap">
          <a href="{% url 'Shop_Application:product_detail' pk=product.pk %}">
          <img src="/media/{{product.mainimage}}" style="width:100%; height:300px;">
          </a>
        </div>
        <figcaption class="info-wrap">
          <h6 class="title"><a href="{% url 'Shop_Application:product_detail' pk=product.pk %}">{{product.name}}</a></h6>
          <div class="action-wrap">
            <div class="price-wrap h5">
              <span class="price-new">&#2547; {{product.price|floatformat:2}}</span>
              <span class="price-old"><strike>&#2547; {{product.old_price|floatformat:2}}</strike></span>
            </div>
          </div>
        </figcaption>
      </figure>
    </div>
    {% endfor %}
  </div>
</div>

{% endblock %}

Ecommerce/templates/Shop_Application/product_detail.html
{% extends 'base.html' %}
{% block body_block %}
<div class="container my-5">
  <div class="card">
    <div class="row">
      <aside class="col-sm-5 border-right">
        <article class="gallery-wrap">
          <div class="img-big-wrap">
            <div>
              <a href="#"><img src="/media/{{object.mainimage}}" style="width:450px"></a>
            </div>
          </div>
        </article>
      </aside>
      <aside class="col-sm-7">
        <article class="">
          <h3 class="title mp-3">{{object.name}}</h3>
          <p class="price-detail-wrap">
            <span class="price h3 text-danger">
              <span class="currency">BDT &#2547;</span><span class="num">{{object.price}}</span>
            </span>
          </p>
          <dl class="item-property">
            <dt>Description</dt>
            <dd>
              <p>{{object.detail_text|linebreaks}}</p>
            </dd>
          </dl>
          <a href="{% url 'Order_Application:add' pk=object.pk %}" class="btn btn-lg btn-outline-dark text-uppercase"> <i class="fas fa-shopping-cart"></i> Add to Cart</a>
        </article>
      </aside>
    </div>
  </div>
</div>
{% endblock %}