Ecommerce/Ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include

#To show media files
from django.conf import settings
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Shop_Application.urls')),
    path('account/', include('Login_Application.urls')),
    path('order/', include('Order_Application.urls')),
    path('payment/', include('Payment_Application.urls'))
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Ecommerce/Login_Application/urls.py
from django.urls import path
from Login_Application import views

app_name = 'Login_Application'


urlpatterns = [
    path('signup/', views.sign_up, name='signup'),
    path('login/', views.login_user, name='login'),
    path('logout/', views.logout_user, name='logout'),
    path('profile/', views.user_profile, name='profile'),
]

Ecommerce/Order_Application/urls.py
from django.urls import path
from Order_Application import views

app_name = 'Order_Application'


urlpatterns = [
     path('add/<pk>/', views.add_to_cart, name="add"),
     path('cart/', views.cart_view, name="cart"),
     path('remove/<pk>/', views.remove_from_cart, name="remove"),
     path('increase/<pk>/', views.increase_cart, name="increase"),
    path('decrease/<pk>/', views.decrease_cart, name="decrease"),
]

Ecommerce/Payment_Application/urls.py
from django.urls import path
from Payment_Application import views

app_name = "Payment_Application"

urlpatterns = [
    path('checkout/', views.checkout, name="checkout"),
    path('pay/', views.payment, name="payment"),
    path('status/', views.complete, name="complete"),
    path('purchase/<val_id>/<tran_id>/', views.purchase, name="purchase"),
    path('orders/', views.order_view, name="orders"),
]

Ecommerce/Shop_Application/urls.py
from django.urls import path
from Shop_Application import views

app_name = 'Shop_Application'

urlpatterns = [
    path('', views.Home.as_view(), name='home'),
    path('product/<pk>/', views.ProductDetail.as_view(), name='product_detail'),
    path('Accessories', views.Accessories, name='accessories'),
    path('Clothing', views.Clothing, name='clothing'),
    path('EyeWear', views.EyeWear, name='eyewear'),
    path('Electronics', views.Electronics, name='electronics'),
    path('Timepieces', views.Timepieces, name='timepieces'),
]

Ecommerce/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.2/css/all.css" rel="stylesheet">
  <link rel="stylesheet" href="{% static 'css/main.css' %}">
  <title>{% block title_block %} WOZTI{% endblock %}</title>
  <style>

    .table table-hover {
      background-color: azure;
    }
    

  .card {
    height: 350px;
    
  }
  .cared-product{
    border: 
  }

  .card-product:after {
    content: "";
    display: table

    clear: both;
    visibility: hidden;
  }
  .card-product .price-new, .card-product .price {
    margin-right: 5px;
  }

  .card-product .price-old {
    color: #999;
  }

  .card-product .img-wrap {
    border-radius: 3px 3px 0 0;

    overflow: hidden;
    position: relative;
    height: 250px;
    text-align: center;
  }

  .card-product .img-wrap img {
    max-height: 100%;
    max-width: 100%;
    object-fit: cover;
  }

  .card-product .info-wrap {
    overflow: hidden;
    background: azure;
    padding: 15px;
    border-top: 1px solid #eee;
  }

  .card-product .action-wrap {
    padding-top: 4px;
    margin-top: 4px;
  }

  .card-product .bottom-wrap {
    padding: 5px;
    border-top: 1px solid #eee;

  }

  .card-product .title {
    margin-top: 0px;
    
  }
  .card-product .title a{
    color: maroon;
  }
  .images a{
    font-size: 40px;
    font-weight: bolder;
     font-style: italic;
    font-color: white;
    text-align: center;

  }

  .navbar-nav a{
     
   font-size: 20px;
    font-weight:600;
     
   
    text-align: center;

  }
  .login .nav-item a{
     margin-right: 30px;
     font-size: 20px;
     color: black;
      font-weight:600;
     
    
    text-align: center;


  }
  .not-login{
     margin-right: 30px;
  }

    .not-login1{
     margin-right: 10px;
  }
    .about {
      margin-left: 20px;
    }
        .about .navbar-nav a{
      margin-left: 10px;
    }
    .categories .dropdown-menu .dropdown-item{
      margin-left: 5px;
      margin-right: 5px;
      text-align: center;
    }
   
  </style>
  
  
  
</head>

<body>

   <nav class="navbar navbar-expand-md navbar-light badge-light">
        <div class="images">
        <a href="{% url 'Shop_Application:home' %}" class="navbar-brand">
            WOZTI
        </a>
        </div>
        <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarCollapse">
            <div class="about">            
              <div class="navbar-nav">
                <a href="{% url 'Shop_Application:home' %}" class="nav-item nav-link active"><i class="fa fa-home" aria-hidden="true"></i>
 Home</a>

                <a href="#" class="nav-item nav-link"><i class="fa fa-phone-square" aria-hidden="true"></i>
Contact</a>
           <div class="categories">
              <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Categories</a>
          <div class="dropdown-menu" aria-labelledby="nabbarDropdown">
            <a class="dropdown-item" href="{% url 'Shop_Application:accessories' %}">Accessories</a>
            <a class="dropdown-item" href="{% url 'Shop_Application:clothing' %}">Clothing</a>
            
            <a class="dropdown-item" href="{% url 'Shop_Application:eyewear' %}">Eye Wear</a>
            <a class="dropdown-item" href="{% url 'Shop_Application:electronics' %}">Electronics</a>
            <a class="dropdown-item" href="{% url 'Shop_Application:timepieces' %}">Time Pieces</a>
            
          </div>
        </li>
      </div>
                
            </div>
          </div>

              <ul class="navbar-nav ml-auto">
              {% if request.user.is_authenticated %}
               <div class="not-login1"> 
              <li class="nav-item">
          <a href="{% url 'Order_Application:cart' %}" class="nav-link">
              <i class="fa fa-shopping-cart"></i> Cart
              <span class="badge badge-light"></span>
          </a>

        </li>
      </div>
        <div class="not-login">
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="fas fa-user-tie"></i> {{request.user.profile.username}}</a>
          <div class="dropdown-menu" aria-labelledby="nabbarDropdown">
            <a class="dropdown-item" href="{% url 'Login_Application:profile' %}">Profile</a>
            <a class="dropdown-item" href="{% url 'Payment_Application:orders' %}">Orders</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="{% url 'Login_Application:logout' %}">Logout</a>
          </div>
        </li>
      </div>
          {% else %}
        <div class="login">
        <li class="nav-item">
          <a href="{% url 'Login_Application:login' %}">Login</a>
        </li>
        {% endif %}
      </div>
    </ul>
  </div>
    </nav>


 






  <div class="container">
    
     <div class="messages container mt-2">
      {% if messages %}
        {% for message in messages %}
          <div {% if message.tags %} class="alert alert-{{message.tags}}{% endif %}" role="alert">
            {{message}}
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          </div>
        {% endfor %}
      {% endif %}
    </div>
    {% block body_block %} {% endblock %}

  </div>

  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

</body>
</html>

Ecommerce/templates/navbar.html
 {% load static %}
 <nav class="navbar navbar-expand-md navbar-light bg-light">
        <a href="{% url 'Shop_Application:home' %}" class="navbar-brand">
            <img src="{% static 'images/logo.png' %}" height="48" width="350"alt="WOZTI">
        </a>
        <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarCollapse">
            <div class="navbar-nav">
                <a href="{% url 'Shop_Application:home' %}" class="nav-item nav-link active"><i class="fa fa-home" aria-hidden="true"></i>
 Home</a>
                <a href="#" class="nav-item nav-link"><i class="fa fa-question-circle" aria-hidden="true"></i>
About</a>
                <a href="#" class="nav-item nav-link"><i class="fa fa-phone-square" aria-hidden="true"></i>
Contact</a>
                
            </div>
              <ul class="navbar-nav ml-auto">
              {% if request.user.is_authenticated %}
              <li class="nav-item">
          <a href="#" class="nav-link">
              <i class="fa fa-shopping-cart"></i> Cart
              <span class="badge badge-light"></span>
          </a>
        </li>
        <li class="nav-item">

        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="fas fa-user-tie"></i> {{request.user.profile.username}}</a>
          <div class="dropdown-menu" aria-labelledby="nabbarDropdown">
            <a class="dropdown-item" href="{% url 'Login_Application:profile' %}">Profile</a>
            <a class="dropdown-item" href="#">Orders</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="{% url 'Login_Application:logout' %}">Logout</a>
          </div>
        </li>
          {% else %}
        <li class="nav-item">
          <a href="{% url 'Login_Application:login' %}">Login</a>
        </li>
        {% endif %}
    </ul>
    </nav>

Ecommerce/templates/navbar2.html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<title></title>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
<script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script>
<style>
    .bs{
        margin: 0px;
    }
</style>
</head>
<body>
<div class="bs">
    <nav class="navbar navbar-expand-md navbar-light bg-light">
        <a href="{% url 'Shop_Application:home' %}" class="navbar-brand">
            <img src="logo.png" height="48" width="250"alt="CoolBrand">
        </a>
        <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarCollapse">
            <div class="navbar-nav">
                <a href="{% url 'Shop_Application:home' %}" class="nav-item nav-link active"><i class="fa fa-home" aria-hidden="true"></i>
 Home</a>
                <a href="#" class="nav-item nav-link"><i class="fa fa-question-circle" aria-hidden="true"></i>
About</a>
                <a href="#" class="nav-item nav-link"><i class="fa fa-phone-square" aria-hidden="true"></i>
Contact</a>
                
            </div>
              <ul class="navbar-nav ml-auto">
              {% if request.user.is_authenticated %}
              <li class="nav-item">
          <a href="#" class="nav-link">
              <i class="fa fa-shopping-cart"></i> Cart
              <span class="badge badge-light"></span>
          </a>
        </li>
        <li class="nav-item">

        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="fas fa-user-tie"></i> {{request.user.profile.username}}</a>
          <div class="dropdown-menu" aria-labelledby="nabbarDropdown">
            <a class="dropdown-item" href="{% url 'Login_Application:profile' %}">Profile</a>
            <a class="dropdown-item" href="#">Orders</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="{% url 'Login_Application:logout' %}">Logout</a>
          </div>
        </li>
          {% else %}
        <li class="nav-item">
          <a href="{% url 'Login_Application:login' %}">Login</a>
        </li>
        {% endif %}
    </ul>
    </nav>
</div>
</body>
</html>